### ISSUE TITLE
Function create_epub to receive complete path

### ISSUE THREAD

**Issue by sjehuda** [dfface/xml2epub#35]
Related to https://github.com/wcember/pypub/issues/30

Greetings

I'm attempting to utilize xml2epub with my Slixfeed XMPP news bot.
```
def generate_epub(text, pathname):
    pathname = pathname.split("/")
    filename = pathname.pop()
    directory = "/".join(pathname)
    book = xml2epub.Epub(filename)
    chapter0 = xml2epub.create_chapter_from_string(text, strict=False)
    book.add_chapter(chapter0)
    book.create_epub(directory, epub_name=filename)
```
The result would yield a filename that was not originally intended.

If my intention is to have `filename_001.epub`, it would turn into `filename001`.

This results in my program failing to locate the generated file.

To solve this, I import module `os` and rename the file.

```
def generate_epub(text, pathname):
    pathname_list = pathname.split("/")
    filename = pathname_list.pop()
    directory = "/".join(pathname_list)
    book = xml2epub.Epub(filename)
    chapter0 = xml2epub.create_chapter_from_string(text, strict=False)
    book.add_chapter(chapter0)
    filename_tmp = "slixfeedepub"
    book.create_epub(directory, epub_name=filename_tmp)
    pathname_tmp = os.path.join(directory, filename_tmp) + ".epub"
    os.rename(pathname_tmp, pathname)
```

Please allow passing a complete path, as it would make workflow more consistent.

---

Here are other functions I use for other filetypes.
```
def generate_html(text, filename):
    with open(filename, 'w') as file:
        file.write(text)

def generate_pdf(text, filename):
    pdfkit.from_string(text, filename)

def generate_markdown(text, filename):
    h2m = html2text.HTML2Text()
    markdown = h2m.handle(text)
    with open(filename, 'w') as file:
        file.write(markdown)
```
Notice that all filenames passed are utilized with no change.

**Comment by sjehuda** [comment]
Here are other functions I use for other filetypes.
```
def generate_html(text, filename):
    with open(filename, 'w') as file:
        file.write(text)

def generate_pdf(text, filename):
    pdfkit.from_string(text, filename)

def generate_markdown(text, filename):
    h2m = html2text.HTML2Text()
    markdown = h2m.handle(text)
    with open(filename, 'w') as file:
        file.write(markdown)
```

**Comment by dfface** [comment]
@sjehuda hello, this problem has been solved in v2.6.5

please refer to https://github.com/dfface/xml2epub/releases/tag/v2.6.5

**Comment by sjehuda** [comment]
Great! I will try it and I will let you know if problem still appears.

**Comment by sjehuda** [comment]
What was the reason to let xml2epub to add file extension on its own?

`absolute_location (Option[str]): The absolute path and file name of the file, excluding the file type suffix (do not contain .epub at the end).`

I expect to add `/path/to/file/name.epub`.

In any case, I am happy for having the new option `absolute_location`.
Thank you for this!

**Comment by sjehuda** [comment]
see changes made to `action.py`; I was required add this code `filename = filename.replace('.epub', '')`
https://gitgud.io/sjehuda/slixfeed/-/commit/b81ff04c0ded4a78db50cbda44e30ad5256c6675

Or this code (might be better)
```
>>> filename = filename.split('.')
>>> filename.pop()
>>> filename = '.'.join(filename)
```
https://gitgud.io/sjehuda/slixfeed/-/commit/926c0341c6899820c1c472c1d344735a3763b269

**Comment by dfface** [comment]
@sjehuda 
Because the `shutil.make_archive` function is used underneath, its first input parameter is what it is.

![image](https://github.com/dfface/xml2epub/assets/49226204/f5181d2b-c088-4f57-929a-c8cd88124ddb)

**Comment by sjehuda** [comment]
Thank you for the elaboration.
Thank you very much for the new feature.

I would like to add an entry of xml2epub to Slixfeed.
Please provide me with these details, if you would:

```
[[about]]
name = "xml2epub"
about = "description"
info = ["""
short description.

Long description.
"""]
url = "URL"
```
